// <auto-generated />
using System;
using Abraham_API1_P2.Server.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Abraham_API1_P2.Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231029003028_Cuarta_ArreglandoFaltaOrtografica")]
    partial class Cuarta_ArreglandoFaltaOrtografica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Abraham_API1_P2.Shared.Models.Entradas", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadProducida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("PesoTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EntradaId");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("Abraham_API1_P2.Shared.Models.EntradasDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CantidadUtilizada")
                        .HasColumnType("REAL");

                    b.Property<int>("EntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("EntradaId");

                    b.ToTable("EntradasDetalle");
                });

            modelBuilder.Entity("Abraham_API1_P2.Shared.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Existencia")
                        .HasColumnType("REAL");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Descripción = "Maní",
                            Existencia = 500.0,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 2,
                            Descripción = "Pistacho",
                            Existencia = 500.0,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 3,
                            Descripción = "Pasas",
                            Existencia = 500.0,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 4,
                            Descripción = "Ciruelas",
                            Existencia = 500.0,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 5,
                            Descripción = "Arándanos",
                            Existencia = 500.0,
                            Tipo = 0
                        },
                        new
                        {
                            ProductoId = 6,
                            Descripción = "Mixto MPP 0.5L lb",
                            Existencia = 0.0,
                            Tipo = 1
                        },
                        new
                        {
                            ProductoId = 7,
                            Descripción = "Mixto MPC 0.5L lb",
                            Existencia = 0.0,
                            Tipo = 1
                        },
                        new
                        {
                            ProductoId = 8,
                            Descripción = "Mixto MPP 0.2L lb",
                            Existencia = 0.0,
                            Tipo = 1
                        });
                });

            modelBuilder.Entity("Abraham_API1_P2.Shared.Models.EntradasDetalle", b =>
                {
                    b.HasOne("Abraham_API1_P2.Shared.Models.Entradas", null)
                        .WithMany("EntradasDetalle")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Abraham_API1_P2.Shared.Models.Entradas", b =>
                {
                    b.Navigation("EntradasDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
